# ICP params
threshold: 1.0
method: p2l
warm_start: true
step : 5
acc_frame_count: 500
strategy: raycasting # sample
loss: huber

# Mapping
depth: 8
min_density: 0.1
n_threads: -1
acc_map_count: 200

# Pre Processing
downsample: true
# normals: range_image
normals: knn_normal
voxel_size: 0.4
crop: true
max_nn: 20
W: 1024
H: 64

# misc
out_dir: results/
debug: false
